# Generated by Django 4.2.6 on 2023-10-11 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opiniones", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="departments",
            field=models.ManyToManyField(to="usuarios.department"),
        ),
        migrations.AddField(
            model_name="opinion",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="usuarios.course"
            ),
        ),
        migrations.AddField(
            model_name="opinion",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="opiniones.teacher"
            ),
        ),
        migrations.AddField(
            model_name="opinion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
