# Generated by Django 4.2 on 2023-11-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_course_code_alter_course_department_and_more'),
        ('opiniones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='course_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha del curso'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='first_time',
            field=models.BooleanField(default=False, verbose_name='Primera vez'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='opiniones.teacher', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='teacher_support',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], verbose_name='Apoyo del profesor'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='theoricity',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], verbose_name='Teoricidad'),
        ),
    ]
